version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    # command: "gunicorn --timeout=30 --workers=2 --bind 0.0.0.0:8000 project.wsgi:application"
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=2 --bind :8000 project.wsgi:application"
    volumes:
      - .:/code
      - static-volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  db:
    #   image: mysql:latest
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password

    volumes:
      #    - "./mysql:/home/adeleke/db_volumes"
      - "./mysql:/var/lib/mysql"
    ports:
      - "3307:3307"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=django_app123
    networks:
      - db_network

  nginx:
    image: nginx:latest
    ports:
      - "3000:8000"
      # - "8000:8000"
      # - "80:8000"
      # This binds port 8000 in the docker to port 3000 in the host port
      # Remember that port 8000 has been exposed in the app servicei
      # Port 8000 is also what the nginx server is listening to in its
      # conf file in config/nginx/djangoapp.conf
    volumes:
      - static-volume:/code/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

  db_network:
    driver: bridge

volumes:
  static-volume:
